/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AchievementRewardsSchema } from '../models/AchievementRewardsSchema.ts';
import { AchievementType } from '../models/AchievementType.ts';
import { HttpFile } from '../http/http.ts';

export class AccountAchievementSchema {
    /**
    * Name of the achievement.
    */
    'name': string;
    /**
    * Code of the achievement. 
    */
    'code': string;
    /**
    * Description of the achievement.
    */
    'description': string;
    /**
    * Points of the achievement. Used for the leaderboard.
    */
    'points': number;
    /**
    * Type of achievement.
    */
    'type': AchievementType;
    'target': string | null;
    /**
    * Total to do.
    */
    'total': number;
    /**
    * Rewards.
    */
    'rewards': AchievementRewardsSchema;
    /**
    * Current progress.
    */
    'current': number;
    'completedAt': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "AchievementType",
            "format": ""
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "string",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        },
        {
            "name": "rewards",
            "baseName": "rewards",
            "type": "AchievementRewardsSchema",
            "format": ""
        },
        {
            "name": "current",
            "baseName": "current",
            "type": "number",
            "format": ""
        },
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return AccountAchievementSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


