/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountStatus } from '../models/AccountStatus';
import { HttpFile } from '../http/http';

export class AccountDetails {
    /**
    * Username.
    */
    'username': string;
    /**
    * Subscribed for the current season.
    */
    'subscribed': boolean;
    /**
    * Member status.
    */
    'status': AccountStatus;
    /**
    * Account badges.
    */
    'badges'?: Array<any>;
    /**
    * Achievement points.
    */
    'achievementsPoints': number;
    /**
    * Banned.
    */
    'banned': boolean;
    /**
    * Ban reason.
    */
    'banReason'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "subscribed",
            "baseName": "subscribed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountStatus",
            "format": ""
        },
        {
            "name": "badges",
            "baseName": "badges",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "achievementsPoints",
            "baseName": "achievements_points",
            "type": "number",
            "format": ""
        },
        {
            "name": "banned",
            "baseName": "banned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "banReason",
            "baseName": "ban_reason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountDetails.attributeTypeMap;
    }

    public constructor() {
    }
}


