/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AccountStatus } from '../models/AccountStatus';
import { HttpFile } from '../http/http';

export class AccountLeaderboardSchema {
    /**
    * Position in the leaderboard.
    */
    'position': number;
    /**
    * Account name.
    */
    'account': string;
    /**
    * Member status.
    */
    'status': AccountStatus;
    /**
    * Achievements points.
    */
    'achievementsPoints': number;
    /**
    * Gold in the account.
    */
    'gold': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "position",
            "baseName": "position",
            "type": "number",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AccountStatus",
            "format": ""
        },
        {
            "name": "achievementsPoints",
            "baseName": "achievements_points",
            "type": "number",
            "format": ""
        },
        {
            "name": "gold",
            "baseName": "gold",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AccountLeaderboardSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


