/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum ActionType {
    Movement = 'movement',
    Fight = 'fight',
    Crafting = 'crafting',
    Gathering = 'gathering',
    BuyGe = 'buy_ge',
    SellGe = 'sell_ge',
    BuyNpc = 'buy_npc',
    SellNpc = 'sell_npc',
    CancelGe = 'cancel_ge',
    DeleteItem = 'delete_item',
    Deposit = 'deposit',
    Withdraw = 'withdraw',
    DepositGold = 'deposit_gold',
    WithdrawGold = 'withdraw_gold',
    Equip = 'equip',
    Unequip = 'unequip',
    Task = 'task',
    ChristmasExchange = 'christmas_exchange',
    Recycling = 'recycling',
    Rest = 'rest',
    Use = 'use',
    BuyBankExpansion = 'buy_bank_expansion'
}
