/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MapSchema } from '../models/MapSchema.ts';
import { HttpFile } from '../http/http.ts';

export class ActiveEventSchema {
    /**
    * Name of the event.
    */
    'name': string;
    /**
    * Code of the event.
    */
    'code': string;
    /**
    * Map of the event.
    */
    'map': MapSchema;
    /**
    * Previous map skin.
    */
    'previousSkin': string;
    /**
    * Duration in minutes.
    */
    'duration': number;
    /**
    * Expiration datetime.
    */
    'expiration': Date;
    /**
    * Start datetime.
    */
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "map",
            "baseName": "map",
            "type": "MapSchema",
            "format": ""
        },
        {
            "name": "previousSkin",
            "baseName": "previous_skin",
            "type": "string",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number",
            "format": ""
        },
        {
            "name": "expiration",
            "baseName": "expiration",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return ActiveEventSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
