/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BadgeConditionSchema } from '../models/BadgeConditionSchema';
import { HttpFile } from '../http/http';

export class BadgeSchema {
    /**
    * Code of the badge. This is the badge\'s unique identifier (ID).
    */
    'code': string;
    'season'?: number | null;
    /**
    * Description of the badge.
    */
    'description': string;
    /**
    * Conditions to get the badge.
    */
    'conditions': Array<BadgeConditionSchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "season",
            "baseName": "season",
            "type": "number",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<BadgeConditionSchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BadgeSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
