/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class BlockedHitsSchema {
    /**
    * The amount of fire hits blocked.
    */
    'fire': number;
    /**
    * The amount of earth hits blocked.
    */
    'earth': number;
    /**
    * The amount of water hits blocked.
    */
    'water': number;
    /**
    * The amount of air hits blocked.
    */
    'air': number;
    /**
    * The amount of total hits blocked.
    */
    'total': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fire",
            "baseName": "fire",
            "type": "number",
            "format": ""
        },
        {
            "name": "earth",
            "baseName": "earth",
            "type": "number",
            "format": ""
        },
        {
            "name": "water",
            "baseName": "water",
            "type": "number",
            "format": ""
        },
        {
            "name": "air",
            "baseName": "air",
            "type": "number",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BlockedHitsSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
