/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CraftSkill } from '../models/CraftSkill';
import { SimpleItemSchema } from '../models/SimpleItemSchema';
import { HttpFile } from '../http/http';

export class CraftSchema {
    /**
    * Skill required to craft the item.
    */
    'skill'?: CraftSkill;
    /**
    * The skill level required to craft the item.
    */
    'level'?: number;
    /**
    * List of items required to craft the item.
    */
    'items'?: Array<SimpleItemSchema>;
    /**
    * Quantity of items crafted.
    */
    'quantity'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "skill",
            "baseName": "skill",
            "type": "CraftSkill",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<SimpleItemSchema>",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CraftSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


