/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class DropRateSchema {
    /**
    * Item code.
    */
    'code': string;
    /**
    * Chance rate. (1/rate)
    */
    'rate': number;
    /**
    * Minimum quantity.
    */
    'minQuantity': number;
    /**
    * Maximum quantity.
    */
    'maxQuantity': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "minQuantity",
            "baseName": "min_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxQuantity",
            "baseName": "max_quantity",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DropRateSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
