/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharacterSchema } from '../models/CharacterSchema';
import { CooldownSchema } from '../models/CooldownSchema';
import { ItemSchema } from '../models/ItemSchema';
import { ItemSlot } from '../models/ItemSlot';
import { HttpFile } from '../http/http';

export class EquipRequestSchema {
    /**
    * Cooldown details.
    */
    'cooldown': CooldownSchema;
    /**
    * Item slot.
    */
    'slot': ItemSlot;
    /**
    * Item details.
    */
    'item': ItemSchema;
    /**
    * Player details.
    */
    'character': CharacterSchema;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cooldown",
            "baseName": "cooldown",
            "type": "CooldownSchema",
            "format": ""
        },
        {
            "name": "slot",
            "baseName": "slot",
            "type": "ItemSlot",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "ItemSchema",
            "format": ""
        },
        {
            "name": "character",
            "baseName": "character",
            "type": "CharacterSchema",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EquipRequestSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


