/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BlockedHitsSchema } from '../models/BlockedHitsSchema';
import { DropSchema } from '../models/DropSchema';
import { FightResult } from '../models/FightResult';
import { HttpFile } from '../http/http';

export class FightSchema {
    /**
    * The amount of xp gained from the fight.
    */
    'xp': number;
    /**
    * The amount of gold gained from the fight.
    */
    'gold': number;
    /**
    * The items dropped from the fight.
    */
    'drops': Array<DropSchema>;
    /**
    * Numbers of the turns of the combat.
    */
    'turns': number;
    /**
    * The amount of blocked hits by the monster.
    */
    'monsterBlockedHits': BlockedHitsSchema;
    /**
    * The amount of blocked hits by the player.
    */
    'playerBlockedHits': BlockedHitsSchema;
    /**
    * The fight logs.
    */
    'logs': Array<string>;
    /**
    * The result of the fight.
    */
    'result': FightResult;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "xp",
            "baseName": "xp",
            "type": "number",
            "format": ""
        },
        {
            "name": "gold",
            "baseName": "gold",
            "type": "number",
            "format": ""
        },
        {
            "name": "drops",
            "baseName": "drops",
            "type": "Array<DropSchema>",
            "format": ""
        },
        {
            "name": "turns",
            "baseName": "turns",
            "type": "number",
            "format": ""
        },
        {
            "name": "monsterBlockedHits",
            "baseName": "monster_blocked_hits",
            "type": "BlockedHitsSchema",
            "format": ""
        },
        {
            "name": "playerBlockedHits",
            "baseName": "player_blocked_hits",
            "type": "BlockedHitsSchema",
            "format": ""
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "result",
            "baseName": "result",
            "type": "FightResult",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FightSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


