/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class GeOrderHistorySchema {
    /**
    * Order id.
    */
    'orderId': string;
    /**
    * Seller account name.
    */
    'seller': string;
    /**
    * Buyer account name.
    */
    'buyer': string;
    /**
    * Item code.
    */
    'code': string;
    /**
    * Item quantity.
    */
    'quantity': number;
    /**
    * Item price per unit.
    */
    'price': number;
    /**
    * Sale datetime.
    */
    'soldAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "order_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "seller",
            "baseName": "seller",
            "type": "string",
            "format": ""
        },
        {
            "name": "buyer",
            "baseName": "buyer",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "soldAt",
            "baseName": "sold_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return GeOrderHistorySchema.attributeTypeMap;
    }

    public constructor() {
    }
}
