/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CharacterSchema } from '../models/CharacterSchema.ts';
import { CooldownSchema } from '../models/CooldownSchema.ts';
import { GETransactionSchema } from '../models/GETransactionSchema.ts';
import { HttpFile } from '../http/http.ts';

export class GETransactionListSchema {
    /**
    * Cooldown details.
    */
    'cooldown': CooldownSchema;
    /**
    * Transaction details.
    */
    'order': GETransactionSchema;
    /**
    * Character details.
    */
    'character': CharacterSchema;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cooldown",
            "baseName": "cooldown",
            "type": "CooldownSchema",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "GETransactionSchema",
            "format": ""
        },
        {
            "name": "character",
            "baseName": "character",
            "type": "CharacterSchema",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GETransactionListSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
