/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export enum ItemType {
    Utility = 'utility',
    BodyArmor = 'body_armor',
    Weapon = 'weapon',
    Resource = 'resource',
    LegArmor = 'leg_armor',
    Helmet = 'helmet',
    Boots = 'boots',
    Shield = 'shield',
    Amulet = 'amulet',
    Ring = 'ring',
    Artifact = 'artifact',
    Currency = 'currency',
    Consumable = 'consumable',
    Rune = 'rune',
    Bag = 'bag'
}
