/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export enum ItemSlot {
    Weapon = 'weapon',
    Shield = 'shield',
    Helmet = 'helmet',
    BodyArmor = 'body_armor',
    LegArmor = 'leg_armor',
    Boots = 'boots',
    Ring1 = 'ring1',
    Ring2 = 'ring2',
    Amulet = 'amulet',
    Artifact1 = 'artifact1',
    Artifact2 = 'artifact2',
    Artifact3 = 'artifact3',
    Utility1 = 'utility1',
    Utility2 = 'utility2',
    Bag = 'bag',
    Rune = 'rune'
}
