/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CraftSchema } from '../models/CraftSchema.ts';
import { SimpleEffectSchema } from '../models/SimpleEffectSchema.ts';
import { HttpFile } from '../http/http.ts';

export class ItemSchema {
    /**
    * Item name.
    */
    'name': string;
    /**
    * Item code. This is the item\'s unique identifier (ID).
    */
    'code': string;
    /**
    * Item level.
    */
    'level': number;
    /**
    * Item type.
    */
    'type': string;
    /**
    * Item subtype.
    */
    'subtype': string;
    /**
    * Item description.
    */
    'description': string;
    /**
    * List of object effects. For equipment, it will include item stats.
    */
    'effects'?: Array<SimpleEffectSchema>;
    'craft'?: CraftSchema | null;
    /**
    * Item tradeable status. A non-tradeable item cannot be exchanged or sold.
    */
    'tradeable': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "subtype",
            "baseName": "subtype",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "effects",
            "baseName": "effects",
            "type": "Array<SimpleEffectSchema>",
            "format": ""
        },
        {
            "name": "craft",
            "baseName": "craft",
            "type": "CraftSchema",
            "format": ""
        },
        {
            "name": "tradeable",
            "baseName": "tradeable",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ItemSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
