/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LogType } from '../models/LogType';
import { HttpFile } from '../http/http';

export class LogSchema {
    /**
    * Character name.
    */
    'character': string;
    /**
    * Account character.
    */
    'account': string;
    /**
    * Type of action.
    */
    'type': LogType;
    /**
    * Description of action.
    */
    'description': string;
    'content': any | null;
    /**
    * Cooldown in seconds.
    */
    'cooldown': number;
    'cooldownExpiration': Date | null;
    /**
    * Datetime of creation.
    */
    'createdAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "character",
            "baseName": "character",
            "type": "string",
            "format": ""
        },
        {
            "name": "account",
            "baseName": "account",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "LogType",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "any",
            "format": ""
        },
        {
            "name": "cooldown",
            "baseName": "cooldown",
            "type": "number",
            "format": ""
        },
        {
            "name": "cooldownExpiration",
            "baseName": "cooldown_expiration",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return LogSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


