/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DropRateSchema } from '../models/DropRateSchema';
import { SimpleEffectSchema } from '../models/SimpleEffectSchema';
import { HttpFile } from '../http/http';

export class MonsterSchema {
    /**
    * Name of the monster.
    */
    'name': string;
    /**
    * The code of the monster. This is the monster\'s unique identifier (ID).
    */
    'code': string;
    /**
    * Monster level.
    */
    'level': number;
    /**
    * Monster hit points.
    */
    'hp': number;
    /**
    * Monster fire attack.
    */
    'attackFire': number;
    /**
    * Monster earth attack.
    */
    'attackEarth': number;
    /**
    * Monster water attack.
    */
    'attackWater': number;
    /**
    * Monster air attack.
    */
    'attackAir': number;
    /**
    * Monster % fire resistance.
    */
    'resFire': number;
    /**
    * Monster % earth resistance.
    */
    'resEarth': number;
    /**
    * Monster % water resistance.
    */
    'resWater': number;
    /**
    * Monster % air resistance.
    */
    'resAir': number;
    /**
    * Monster % critical strike.
    */
    'criticalStrike': number;
    /**
    * List of effects.
    */
    'effects'?: Array<SimpleEffectSchema>;
    /**
    * Monster minimum gold drop. 
    */
    'minGold': number;
    /**
    * Monster maximum gold drop. 
    */
    'maxGold': number;
    /**
    * Monster drops. This is a list of items that the monster drops after killing the monster. 
    */
    'drops': Array<DropRateSchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "hp",
            "baseName": "hp",
            "type": "number",
            "format": ""
        },
        {
            "name": "attackFire",
            "baseName": "attack_fire",
            "type": "number",
            "format": ""
        },
        {
            "name": "attackEarth",
            "baseName": "attack_earth",
            "type": "number",
            "format": ""
        },
        {
            "name": "attackWater",
            "baseName": "attack_water",
            "type": "number",
            "format": ""
        },
        {
            "name": "attackAir",
            "baseName": "attack_air",
            "type": "number",
            "format": ""
        },
        {
            "name": "resFire",
            "baseName": "res_fire",
            "type": "number",
            "format": ""
        },
        {
            "name": "resEarth",
            "baseName": "res_earth",
            "type": "number",
            "format": ""
        },
        {
            "name": "resWater",
            "baseName": "res_water",
            "type": "number",
            "format": ""
        },
        {
            "name": "resAir",
            "baseName": "res_air",
            "type": "number",
            "format": ""
        },
        {
            "name": "criticalStrike",
            "baseName": "critical_strike",
            "type": "number",
            "format": ""
        },
        {
            "name": "effects",
            "baseName": "effects",
            "type": "Array<SimpleEffectSchema>",
            "format": ""
        },
        {
            "name": "minGold",
            "baseName": "min_gold",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxGold",
            "baseName": "max_gold",
            "type": "number",
            "format": ""
        },
        {
            "name": "drops",
            "baseName": "drops",
            "type": "Array<DropRateSchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MonsterSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
