/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { NPCType } from '../models/NPCType';
import { HttpFile } from '../http/http';

export class NPCSchema {
    /**
    * Name of the NPC.
    */
    'name': string;
    /**
    * The code of the NPC. This is the NPC\'s unique identifier (ID).
    */
    'code': string;
    /**
    * Description of the NPC.
    */
    'description': string;
    /**
    * Type of the NPC.
    */
    'type': NPCType;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "NPCType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return NPCSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


