/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DropRateSchema } from '../models/DropRateSchema.ts';
import { GatheringSkill } from '../models/GatheringSkill.ts';
import { HttpFile } from '../http/http.ts';

export class ResourceSchema {
    /**
    * The name of the resource
    */
    'name': string;
    /**
    * The code of the resource. This is the resource\'s unique identifier (ID).
    */
    'code': string;
    /**
    * The skill required to gather this resource.
    */
    'skill': GatheringSkill;
    /**
    * The skill level required to gather this resource.
    */
    'level': number;
    /**
    * The drops of this resource.
    */
    'drops': Array<DropRateSchema>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "skill",
            "baseName": "skill",
            "type": "GatheringSkill",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "drops",
            "baseName": "drops",
            "type": "Array<DropRateSchema>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ResourceSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


