/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AnnouncementSchema } from '../models/AnnouncementSchema.ts';
import { HttpFile } from '../http/http.ts';

export class StatusSchema {
    /**
    * Server status
    */
    'status': string;
    /**
    * Game version.
    */
    'version': string;
    /**
    * Maximum level.
    */
    'maxLevel': number;
    /**
    * Characters online.
    */
    'charactersOnline': number;
    /**
    * Server time.
    */
    'serverTime': Date;
    /**
    * Server announcements.
    */
    'announcements': Array<AnnouncementSchema>;
    /**
    * Last server wipe.
    */
    'lastWipe': string;
    /**
    * Next server wipe.
    */
    'nextWipe': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxLevel",
            "baseName": "max_level",
            "type": "number",
            "format": ""
        },
        {
            "name": "charactersOnline",
            "baseName": "characters_online",
            "type": "number",
            "format": ""
        },
        {
            "name": "serverTime",
            "baseName": "server_time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "announcements",
            "baseName": "announcements",
            "type": "Array<AnnouncementSchema>",
            "format": ""
        },
        {
            "name": "lastWipe",
            "baseName": "last_wipe",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextWipe",
            "baseName": "next_wipe",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatusSchema.attributeTypeMap;
    }

    public constructor() {
    }
}
