/**
 * Artifacts API
 *  Artifacts is an API-based MMO game where you can manage 5 characters to explore, fight, gather resources, craft items and much more.  Website: https://artifactsmmo.com/  Documentation: https://docs.artifactsmmo.com/  OpenAPI Spec: https://api.artifactsmmo.com/openapi.json 
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RewardsSchema } from '../models/RewardsSchema.ts';
import { TaskType } from '../models/TaskType.ts';
import { HttpFile } from '../http/http.ts';

export class TaskFullSchema {
    /**
    * Task objective.
    */
    'code': string;
    /**
    * Task level.
    */
    'level': number;
    /**
    * The type of task.
    */
    'type': TaskType;
    /**
    * Minimum amount of task.
    */
    'minQuantity': number;
    /**
    * Maximum amount of task.
    */
    'maxQuantity': number;
    'skill': string | null;
    /**
    * Rewards.
    */
    'rewards': RewardsSchema;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TaskType",
            "format": ""
        },
        {
            "name": "minQuantity",
            "baseName": "min_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxQuantity",
            "baseName": "max_quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "skill",
            "baseName": "skill",
            "type": "string",
            "format": ""
        },
        {
            "name": "rewards",
            "baseName": "rewards",
            "type": "RewardsSchema",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskFullSchema.attributeTypeMap;
    }

    public constructor() {
    }
}


